### ISSUE TITLE
Timeout for ping

### ISSUE THREAD

**Issue by Maclay74** [LouisOuellet/php-net#1]
Hey, I see in annotations for ping method an additional argument for timeout, but it wasn't implemented or was removed at some point?

```php
 /**
   * Send a ping.
   *
   * @param  string  $ip
   * @param  int  $timeout
   * @return string|bool Return latency on success and false on failure
   * @throws Exception
   */
public function ping($ip){
```

**Comment by LouisOuellet** [comment]
Because of the elevated privileges required to run ping with a small timeout value (-i), I chose to remove it before releasing the very first version. I guess I forgot to remove the annotation.

I need to work on those commit messages. Back then I didn't know much about GitHub and just started publishing a bunch of my PHP scripts on GitHub and Composer. So sorry for the lack of history. Future commits will be more verbose.

**Comment by Maclay74** [comment]
No problem, thanks for the explanation!
